<a href="https://colab.research.google.com/github/VijayRameshkumar/TensorFlow_Keras_2.0/blob/master/02.%20Bank_customer_churn%20/%20ANN_Bank_customer_churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install tensorflow==2.0 --upgrade
! pip install tensorflow-gpu==2.0 --upgrade
import tensorflow as tf


Requirement already up-to-date: tensorflow==2.0 in /usr/local/lib/python3.6/dist-packages (2.0.0)
Requirement already up-to-date: tensorflow-gpu==2.0 in /usr/local/lib/python3.6/dist-packages (2.0.0)


In [2]:
print(tf.__version__)

2.0.0


In [0]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


**1. Data - Preparation**

In [0]:
df = pd.read_csv("/content/drive/My Drive/test/bank-customer-churn-modeling/Churn_Modelling.csv")

In [7]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
x = df.drop(labels=['CustomerId', 'Surname', 'RowNumber', 'Exited'], axis=1)
y = df['Exited']

In [9]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [0]:
cols = x.columns

In [11]:
x.nunique()

CreditScore         460
Geography             3
Gender                2
Age                  70
Tenure               11
Balance            6382
NumOfProducts         4
HasCrCard             2
IsActiveMember        2
EstimatedSalary    9999
dtype: int64

**2. Pre - Processing**

In [0]:
from sklearn.preprocessing import LabelEncoder

In [13]:
encoder = LabelEncoder()
x['Geography'] = encoder.fit_transform(x['Geography'])
x.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [14]:
x['Gender'] = encoder.fit_transform(x['Gender'])
x.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [15]:
x = pd.get_dummies(x, drop_first=True, columns=['Geography'])
x.head()

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1

[5 rows x 11 columns]

**3. Feature Standardization**

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state = 0, stratify = y)

In [0]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [19]:
xtrain

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

**4. Build ANN model**

In [0]:
model = Sequential()
model.add(Dense(x.shape[1], activation='relu', input_dim=x.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [21]:
x.shape[1]

11

In [0]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [23]:
model.fit(xtrain, ytrain.to_numpy(), batch_size=10, epochs=10, verbose=1)

Train on 8000 samples
Epoch 1/10
8000/8000 [==============================] - 2s 258us/sample - loss: 0.4602 - accuracy: 0.8062
Epoch 2/10
8000/8000 [==============================] - 1s 176us/sample - loss: 0.4058 - accuracy: 0.8296
Epoch 3/10
8000/8000 [==============================] - 1s 175us/sample - loss: 0.3656 - accuracy: 0.8493
Epoch 4/10
8000/8000 [==============================] - 1s 179us/sample - loss: 0.3506 - accuracy: 0.8555
Epoch 5/10
8000/8000 [==============================] - 1s 176us/sample - loss: 0.3451 - accuracy: 0.8579
Epoch 6/10
8000/8000 [==============================] - 1s 186us/sample - loss: 0.3400 - accuracy: 0.8591
Epoch 7/10
8000/8000 [==============================] - 1s 184us/sample - loss: 0.3374 - accuracy: 0.8604
Epoch 8/10
8000/8000 [==============================] - 1s 187us/sample - loss: 0.3352 - accuracy: 0.8610
Epoch 9/10
8000/8000 [==============================] - 2s 191us/sample - loss: 0.3324 - accuracy: 0.8643
Epoch 10/10
8000/8000 [=

In [0]:
y_pred = model.predict_classes(xtest)

In [25]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int32)

In [26]:
ytest

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [27]:
model.evaluate(xtest, ytest.to_numpy())

2000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.34860446500778197, 0.855]

**5. Metrics - Accuracy**

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [29]:
confusion_matrix(ytest, y_pred)

array([[1529,   64],
       [ 226,  181]])